# Generated by Django 4.1.1 on 2022-09-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('EmailID', models.EmailField(max_length=254, unique=True)),
                ('Age', models.IntegerField(default=1)),
                ('Address', models.TextField(default=None)),
            ],
        ),
    ]
